log_format gateway_logs '$remote_addr - $host [$time_local] '
                        '"$request" $status '
                        'upstream=$upstream_addr '
                        'request_time=$request_time '
                        'upstream_time=$upstream_response_time';

server {

    listen 80;

    access_log /var/log/nginx/access.log gateway_logs;

    location /users {
        proxy_pass http://user-service:8080/users;
    }

    location /tasks {
        proxy_pass http://task-service:8080/tasks;
    }

    location /files/upload {
        proxy_pass http://file-service:8080/files/upload;
    }

    location /notifications {
        proxy_pass http://notification-service:8080/notifications;
    }

}
