server {

    listen 80;

    location /users {
        proxy_pass http://localhost:8081/users;
    }

    location /tasks {
        proxy_pass http://localhost:8082/tasks;
    }

    location /files/upload {
        proxy_pass http://localhost:8083/files/upload;
    }

    location /notifications {
        proxy_pass http://localhost:8084/notifications;
    }

}
